package ltypes

type GPTCompletionMessage struct {
	// The contents of the message.
	Content string `json:"content"`

	// The role of the messages author
	Role string `json:"role"`

	// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
	Name string `json:"name,omitempty"`

	// Tool call that this message is responding to.
	ToolCallId string `json:"tool_call_id,omitempty"`

	// The tool calls generated by the model, such as function calls.
	ToolCalls []*GPTCompletionToolCall `json:"tool_calls,omitempty"`
}

type GPTCompletionToolCall struct {
	// The ID of the tool call.
	ID string `json:"id"`

	// The type of the tool. Currently, only function is supported.
	Type string `json:"type"`

	// The function that the model called.
	Function *GPTToolCallFunction `json:"function"`
}

type GPTToolCallFunction struct {
	// The name of the function to call.
	Name string `json:"name"`

	// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
	Arguments string `json:"arguments"`
}
